### PR TITLE
WIP: Add a dashboard to show depot statuses

### PR DESCRIPTION
**Pull request by richardc**
This set of changes adds a dashboard that gives you an overview of the depots you have.  It's mostly just adding to the gui, though each depot class now has to provide a `get_status_items` method in its protocol to return a list of LocalisedString that describe its status.

It's a tool I've found myself wanting, if only as a quick way of seeing that the network-id of two depots is the same as expected (accidental breaks in road by trees is a killer)

Currently it's bound to ALT+T for Transport Drones.  There's also a shortcut bar button.

In mind it's emulating looking at the train gui to see what's flowing.

Clicking the buttons zooms the map to the depot.

It's 90% the gui code from Teleporter, some assets from Shortcuts (for the shortcut-bar-button), and a bunch of guesswork and glue.

I'm calling it WIP for now as there are a couple of things I think would need to be tidied up to call it finished that I plan to get to:

- [ ] Sorting.  It's built using the data right out of the common depot.  Not sure what a logical/stable sort order would be as depots are all named the same
- [ ] Periodic/on-tick updates - currently only fetches data when the gui is made
- [ ] Get a better shortcut bar icon that says Transport Drones in some way (maybe the technology icon makes sense)
- [ ] Bits of missing localisation to re-add
- [ ] Maybe hiding some of the debuggier outputs behind settings?
 
It could also do with a bit of a rebase as there are a bunch of commits that cancel each other out.

Opening now as WIP though, as I'm open to any feedback/direction as to what to improve, or if you think this is a bad idea.

This is my first time hacking on a factorio mod, so a lot of it is copy and paste from other mods and google searches, I've found this a very pleasant codebase to work on/steal from though.

### CODE REVIEW

**Comment by richardc** [comment]
After a few hours of use on a non-trivial map there's a couple more interactions that feel like they need to be added:

- [ ] Ability to select/filter based on depot type - probably checkboxes at the bottom
- [ ] Ability to focus on a few depots
- [ ] Or maybe a break-out inspector that shows you just the depot you just moused-over
- [ ] Wider than just 4 columns (maybe an option)

Ability to zoom by click wasn't that useful, so I might make clicking the button the interaction to set a focused depot.

Looking beyond the current implementation it'd maybe be useful to have a 'Road Sign' item that can be placed on/adjacent to a road to give it a symbolic name.  Then you could put signs down at say 'main bus' and 'mining outpost', then the dashboard would tell you the signs that a depot can reach by those names, and they'd be durable across road-network merges.

**Comment by Klonan** [comment]
This is a pretty significant PR,
I think it will be nice, but I am also aware of how GUIs have this special way of becoming a nightmare to maintain.

I will take a look more deeply at your PR later on in the week, (after more stabilisation of the codebase on my end)

**Comment by richardc** [comment]
Absolutely.  I wouldn't want to push extra work onto you.  With your blessing (and cooperation by adding more information about  the state of the depots/road network via the remoting interface) this could easily be span into an optional module say, Transport Drones Dashboard, which I could maintain.

**Comment by Klonan** [comment]
I am not sure the layout/format of the GUI makes the most sense for a dashboard/overview GUI.

I see the inspiration from Teleporters, but there are different requirements here

I would think, a list view might be more useful, showing each road network separately, and showing lists for different types of depots within that

I'll think about it a bit more

**Comment by Klonan** [comment]
I am starting to write a GUI, it will be really tightly integrated, and I'm doing some large refactoring to make it more possible

I hope the GUI fun you had taught you well, GUI is a right pain and a real joy both at the same time. I will probably copy paste some of the things you added, but overall I just need to write it integrated from scratch

**Comment by richardc** [comment]
I had meant to iterate on this some more but I got distracted by other side projects, so 👍 to closing this off.

Doing bolder refactors to get it integrated well makes a lot of sense, I look forward to seeing where you take it.

**Pull request closed without merging**
